# Builds the SYNTHETIC fixtures for the Product Hardening manual session (manual-qa/v2-hardening-pack.md).
# Everything is generated: no real names, e-mail addresses, paths or user data. Safe to delete afterwards.
#
#   powershell -File desktop\scripts\make-hardening-pack.ps1 [-Out <folder>] [-BigBackupMiB 420] [-DropFileGiB 1]
#
# Writes (under -Out):
#   data-root\                  a seeded app data folder (run the app with LOCALAPPDATA pointing at it)
#   v1\normal\                  small valid V1 backups (r-min, r-full)
#   v1\<CJK folder>\            the same backups under a folder whose name has CJK characters
#   v1\blocked\                 not-a-backup, a truncated backup, a V2 archive-like file (M3)
#   v1\big\big-backup.json      a V1 backup with -BigBackupMiB of decoded media (M7, D2-style load)
#   media\                      a small PNG and WAV (M-U7), plus drop-1GiB.bin (D2)
#   text\long-typing-text.txt   a >= 3 000 character mixed Latin / CJK passage (M-T2a, M-T2b, M-T2d)
param(
  [string]$Out = (Join-Path $env:TEMP "qs-hardening-pack"),
  [int]$BigBackupMiB = 420,
  [int]$DropFileGiB = 1
)
$ErrorActionPreference = "Stop"
$desktop = Split-Path -Parent $PSScriptRoot
Set-Location $desktop
. (Join-Path $desktop "scripts\env.ps1")

Write-Host "Building the scenario helper..."
cargo build -p qs-scenarios --bin qs-scenario
if ($LASTEXITCODE -ne 0) { throw "build failed" }

New-Item -ItemType Directory -Force $Out | Out-Null
$cjk = -join ([char[]](0x4E2D, 0x6587, 0x30D5, 0x30A9, 0x30EB, 0x30C0)) + "-cjk"   # "zhong wen" + katakana "foruda"
$dirs = @("v1\normal", "v1\$cjk", "v1\blocked", "v1\big", "media", "text")
foreach ($d in $dirs) { New-Item -ItemType Directory -Force (Join-Path $Out $d) | Out-Null }

# --- small valid V1 backups (generated by V1's own producer; committed fixtures)
$fx = Join-Path $desktop "core\migrate_v1\tests\fixtures"
foreach ($f in @("r-min.json", "r-full.json")) {
  Copy-Item (Join-Path $fx $f) (Join-Path $Out "v1\normal\$f") -Force
  Copy-Item (Join-Path $fx $f) (Join-Path $Out "v1\$cjk\$f") -Force
}

# --- blocked inputs (M3)
Set-Content -Path (Join-Path $Out "v1\blocked\not-a-backup.json") -Value '{"hello":"world"}' -Encoding ascii
$full = [IO.File]::ReadAllBytes((Join-Path $fx "r-full.json"))
$half = New-Object byte[] ([int]($full.Length / 2))
[Array]::Copy($full, $half, $half.Length)
[IO.File]::WriteAllBytes((Join-Path $Out "v1\blocked\truncated-backup.json"), $half)
[IO.File]::WriteAllBytes((Join-Path $Out "v1\blocked\looks-like-v2.qsarchive"), [Text.Encoding]::ASCII.GetBytes("QSARCHIVE-not-really"))

# --- big backup (M7)
$big = Join-Path $Out "v1\big\big-backup.json"
if (-not (Test-Path $big)) {
  Write-Host "Generating a V1 backup with $BigBackupMiB MiB of media..."
  & (Join-Path $desktop "target\debug\qs-scenario.exe") gen-big $big $BigBackupMiB 4
  if ($LASTEXITCODE -ne 0) { throw "gen-big failed" }
}

# --- media (M-U7) and the large drop file (D2)
[IO.File]::WriteAllBytes((Join-Path $Out "media\pixel.png"), [Convert]::FromBase64String("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="))
$rate = 8000; $n = $rate  # one second, 8-bit mono 440 Hz tone
$pcm = New-Object byte[] $n
for ($i = 0; $i -lt $n; $i++) { $pcm[$i] = [byte](128 + 60 * [Math]::Sin(2 * [Math]::PI * 440 * $i / $rate)) }
$ms = New-Object IO.MemoryStream
$bw = New-Object IO.BinaryWriter $ms
$bw.Write([Text.Encoding]::ASCII.GetBytes("RIFF")); $bw.Write([int](36 + $n)); $bw.Write([Text.Encoding]::ASCII.GetBytes("WAVEfmt "))
$bw.Write([int]16); $bw.Write([int16]1); $bw.Write([int16]1); $bw.Write([int]$rate); $bw.Write([int]$rate); $bw.Write([int16]1); $bw.Write([int16]8)
$bw.Write([Text.Encoding]::ASCII.GetBytes("data")); $bw.Write([int]$n); $bw.Write($pcm); $bw.Flush()
[IO.File]::WriteAllBytes((Join-Path $Out "media\tone.wav"), $ms.ToArray())

$drop = Join-Path $Out ("media\drop-{0}GiB.bin" -f $DropFileGiB)
if (-not (Test-Path $drop) -or (Get-Item $drop).Length -lt ([int64]$DropFileGiB * 1GB)) {
  Write-Host "Writing a $DropFileGiB GiB synthetic file..."
  $buf = New-Object byte[] (1MB)
  (New-Object Random 20261003).NextBytes($buf)
  $fs = [IO.File]::Create($drop)
  try { for ($i = 0; $i -lt ($DropFileGiB * 1024); $i++) { $fs.Write($buf, 0, $buf.Length) } } finally { $fs.Dispose() }
}

# --- a long, mixed-script typing passage (>= 3 000 characters)
$cjkLine = -join ([char[]](0x732B, 0x306F, 0x5BDD, 0x3066, 0x3044, 0x308B, 0x3002, 0x72AC, 0x306F, 0x8D70, 0x308B, 0x3002))
$parts = @()
for ($i = 1; $i -le 28; $i++) {
  $parts += "Paragraph $i. The quick brown fox jumps over the lazy dog while the synthetic reader keeps typing steadily, because careful practice is built from many small, calm repetitions. $cjkLine"
}
Set-Content -Path (Join-Path $Out "text\long-typing-text.txt") -Value ($parts -join "`n") -Encoding utf8

# --- seeded data root for the Final UI session (does not touch real data)
Write-Host "Seeding a sample data folder..."
node (Join-Path $desktop "ui\selftest\seed-data-root.mjs") (Join-Path $Out "data-root")
if ($LASTEXITCODE -ne 0) { throw "seeding failed" }

Write-Host ""
Write-Host "Pack ready: $Out"
Write-Host "Run the app on the sample data:  `$env:LOCALAPPDATA = '$Out\data-root'; & '<path to>\quiz-studio.exe'"
