// Shared UI strings: navigation, domains, intents, states and common actions. English | Simplified Chinese, side by side.
import { defineStrings } from '../i18n.js';

defineStrings({
  'common.ok': ['OK', '确定'],
  'common.cancel': ['Cancel', '取消'],
  'common.close': ['Close', '关闭'],
  'common.save': ['Save', '保存'],
  'common.delete': ['Delete', '删除'],
  'common.edit': ['Edit', '编辑'],
  'common.start': ['Start', '开始'],
  'common.back': ['Back', '返回'],
  'common.loading': ['Loading…', '正在载入…'],
  'common.none': ['None', '无'],
  'common.untitled': ['(untitled)', '（无标题）'],
  'common.error': ['Something went wrong: {message}', '出错了：{message}'],
  'common.items': ['{n} items', '{n} 项'],
  'common.questions': ['{n} questions', '{n} 题'],
  'common.sentences': ['{n} sentences', '{n} 句'],
  'common.characters': ['{n} characters', '{n} 个字符'],
  'common.search': ['Search', '搜索'],
  'common.yes': ['Yes', '是'],
  'common.no': ['No', '否'],

  'nav.today': ['Today', '今日'],
  'nav.calendar': ['Calendar', '日历'],
  'nav.library': ['Library', '资料库'],
  'nav.history': ['Evidence history', '证据历史'],
  'nav.review': ['Review', '批改台'],
  'nav.exchange': ['Exchange & backup', '交换与备份'],
  'nav.settings': ['Settings', '设置'],
  'nav.views': ['Views', '视图'],
  'nav.domains': ['Task domains', '任务域'],
  'nav.dueBadge': ['{n} due or overdue', '{n} 项到期或逾期'],
  'nav.decideBadge': ['{n} dates waiting for your decision', '{n} 个日期待你决定'],
  'nav.offline': ['Offline · data stays on this computer', '离线 · 数据保存在本机'],
  'nav.storeHealthy': ['Store healthy', '数据存储正常'],
  'nav.storeAttention': ['Store needs attention', '数据存储需要处理'],

  'domain.objective': ['Objective', '客观题'],
  'domain.translation': ['Translation', '翻译'],
  'domain.typing': ['Typing', '跟打'],
  'domain.all': ['All', '全部'],

  'intent.practice': ['Practice', '练习'],
  'intent.test': ['Test', '测试'],
  'feedback.instant': ['Instant feedback', '即时反馈'],
  'feedback.submit-at-end': ['Feedback at the end', '交卷后反馈'],

  'state.due': ['Due', '今日到期'],
  'state.overdue': ['Overdue', '已逾期'],
  'state.scheduled': ['Scheduled', '已安排'],
  'state.fulfilled': ['Done', '已完成'],
  'state.cancelled': ['Cancelled', '已取消'],
  'owner.user': ['Date set by you', '你安排的日期'],
  'owner.engine': ['Date proposed by the app', '应用安排的日期'],

  'mark.unknown': ["I don't know this", '不会'],
  'mark.uncertain': ["I'm not sure", '不确定'],
  'mark.should_know': ['I should know this', '应该会'],

  'start.mediaUnavailable': ['The image or audio of this paper cannot be shown, so it was not started. {reasons}', '这份试卷的图片或音频无法显示，所以没有开始。{reasons}'],
  'start.gone': ['This material no longer exists.', '这份材料已经不存在。'],
  'start.notReady': ['This material is not ready to practice yet.', '这份材料还不能用来练习。'],
  'start.failed': ['Could not start: {message}', '无法开始：{message}'],
  'start.resumeFailed': ['This session cannot be resumed ({message}). You can discard it.', '这次练习无法恢复（{message}）。你可以放弃它。'],
  'practice.retryGone': ['The source text no longer exists, so it cannot be retried.', '原文已不存在，无法重做。'],
  'practice.retryFailed': ['The retry could not be started: {message}', '无法开始重做：{message}'],
  'practice.left': ['Progress saved. You can resume it from Today.', '进度已保存，可以在“今日”继续。'],
  'practice.discarded': ['Session discarded. Nothing was recorded.', '已放弃这次练习，没有记录任何结果。'],
});
