// Focused Practice strings (English | Simplified Chinese). The words the learner sees while practicing; the engines never
// see them, so a different language can never change what is revealed or recorded.
import { defineStrings } from '../i18n.js';

defineStrings({
  // ---- frame
  'pr.domain.objective': ['Objective', '客观题'],
  'pr.domain.translation': ['Translation', '翻译'],
  'pr.domain.typing': ['Typing', '跟打'],
  'pr.frame': ['Focused practice', '专注练习'],
  'pr.progress': ['Progress', '进度'],
  'pr.exit': ['Exit', '退出'],
  'pr.done': ['Done', '完成'],
  'pr.resultSaveFailed': ['The result could not be saved - {message}. Your answers are kept; try again.', '结果无法保存 —— {message}。你的作答仍然保留，请再试一次。'],
  'pr.progressSaveFailed': ['Your progress could not be saved: {message}', '进度无法保存：{message}'],
  'pr.leave.title': ['Leave this practice?', '离开这次练习？'],
  'pr.leave.body': ['Your progress is saved. You can resume it later from where you stopped, or discard it - nothing is recorded as a result either way until you finish.', '进度已保存。你可以之后接着做，也可以放弃它 —— 无论哪种，在你完成之前都不会记录任何结果。'],
  'pr.leave.keep': ['Keep practicing', '继续练习'],
  'pr.leave.save': ['Save and leave', '保存并离开'],
  'pr.leave.discard': ['Discard session', '放弃本次练习'],
  'pr.discard.title': ['Discard this session?', '放弃这次练习？'],
  'pr.discard.body': ['The saved progress is deleted. No result is recorded.', '已保存的进度会被删除，不会记录任何结果。'],
  'pr.discard.cancel': ['Cancel', '取消'],
  'pr.discard.confirm': ['Discard', '放弃'],
  'pr.discard.failed': ['The session could not be discarded: {message}. Your progress is unchanged; try again.', '无法放弃这次练习：{message}。你的进度没有变化，请再试一次。'],
  'pr.previous': ['Previous', '上一个'],
  'pr.next': ['Next', '下一个'],
  'pr.finish': ['Finish', '完成'],
  'pr.remove': ['Remove', '移除'],
  'pr.saved': ['Saved', '已保存'],
  // ---- labels
  'pr.kind.unknown': ["I don't know this", '不会'],
  'pr.kind.uncertain': ["I'm not sure", '不确定'],
  'pr.kind.should_know': ['I should know this', '应该会'],
  'pr.type.single': ['Single choice', '单选题'],
  'pr.type.multiple': ['Multiple choice', '多选题'],
  'pr.type.blank': ['Fill in the blank', '填空题'],
  'pr.type.truefalse': ['True or false', '判断题'],
  'pr.type.matching': ['Matching', '匹配题'],
  // ---- Objective
  'pr.obj.image': ['Image', '图片'],
  'pr.obj.audio': ['Audio', '音频'],
  'pr.obj.imageGone': ['The image for this question cannot be shown.', '这道题的图片无法显示。'],
  'pr.obj.audioGone': ['The audio for this question cannot be played.', '这道题的音频无法播放。'],
  'pr.obj.tag': ['Objective · {intent} · {timing}', '客观题 · {intent} · {timing}'],
  'pr.obj.intent.test': ['Test', '测试'],
  'pr.obj.intent.practice': ['Practice', '练习'],
  'pr.obj.timing.instant': ['instant feedback', '即时反馈'],
  'pr.obj.timing.end': ['feedback at the end', '交卷后反馈'],
  'pr.obj.paper': ['Paper', '试卷'],
  'pr.obj.srCorrect': ['Correct answer. ', '正确答案。'],
  'pr.obj.srWrong': ['Your answer, incorrect. ', '你的答案，错误。'],
  'pr.obj.srAnswer': ['Your answer. ', '你的答案。'],
  'pr.obj.selectAll': ['Select all that apply.', '选出所有正确的选项。'],
  'pr.obj.true': ['True', '正确'],
  'pr.obj.false': ['False', '错误'],
  'pr.obj.enter': ['Enter', '输入'],
  'pr.obj.yourAnswer': ['Your answer', '你的答案'],
  'pr.obj.choose': ['Choose…', '请选择…'],
  'pr.obj.correct': ['Correct', '正确'],
  'pr.obj.incorrectMatch': ['Incorrect. Correct match: {right}', '错误。正确的配对：{right}'],
  'pr.obj.notQuite': ['Not quite', '不太对'],
  'pr.obj.explanation': ['Explanation', '解析'],
  'pr.obj.questions': ['Questions', '题目'],
  'pr.obj.chip': ['Question {n}, {answered}{graded}', '第 {n} 题，{answered}{graded}'],
  'pr.obj.chip.answered': ['answered', '已作答'],
  'pr.obj.chip.notAnswered': ['not answered', '未作答'],
  'pr.obj.chip.correct': [', correct', '，正确'],
  'pr.obj.chip.incorrect': [', incorrect', '，错误'],
  'pr.obj.submit.title': ['Submit the paper?', '交卷？'],
  'pr.obj.submit.body': ['Answers cannot be changed after you submit.', '交卷之后不能再修改答案。'],
  'pr.obj.submit.keep': ['Keep working', '继续答题'],
  'pr.obj.submit.confirm': ['Submit paper', '交卷'],
  'pr.obj.tagDone': ['Objective · {intent} · submitted', '客观题 · {intent} · 已交卷'],
  'pr.obj.submitted': ['Submitted', '已交卷'],
  'pr.obj.summary': ['Paper submitted. {correct} of {total} correct.', '已交卷。答对 {correct} / {total} 题。'],
  'pr.obj.result': ['Result', '结果'],
  'pr.obj.saved': ['Saved as a learning record.', '已保存为一条学习记录。'],
  'pr.obj.yourAnswerColon': ['Your answer: ', '你的答案：'],
  'pr.obj.incorrect': ['Incorrect', '错误'],
  'pr.obj.retry': ['Retry the {n} incorrect question(s)', '重做答错的 {n} 道题'],
  'pr.obj.progress': ['{n} of {total} answered', '已作答 {n} / {total}'],
  'pr.obj.unanswered': ['{n} question(s) are unanswered and will count as incorrect. Answers cannot be changed after you submit.', '有 {n} 道题未作答，将按错误计算。交卷之后不能再修改答案。'],
  'pr.obj.scoreOf': ['{correct} of {total}', '{correct} / {total}'],
  'pr.obj.scoreRest': [' correct ({percent}%)', ' 题正确（{percent}%）'],
  'pr.obj.noAnswer': ['no answer', '未作答'],
  'pr.obj.announce': ['{verdict}. {label}: {answer}.{explanation}', '{verdict}。{label}：{answer}。{explanation}'],
  'pr.obj.announceExpl': [' Explanation: {text}', ' 解析：{text}'],
  'pr.obj.check': ['Check answer', '检查答案'],
  'pr.obj.submitPaper': ['Submit paper', '交卷'],
  'pr.obj.questionOf': ['Question {n} of {total}', '第 {n} 题 / 共 {total} 题'],
  // ---- Translation
  'pr.tr.tag': ['Translation · {intent}{langs}', '翻译 · {intent}{langs}'],
  'pr.tr.tagSaved': ['Translation · saved', '翻译 · 已保存'],
  'pr.tr.progress': ['{n} of {total} translated', '已翻译 {n} / {total}'],
  'pr.tr.emptyWarn': ['{n} sentence(s) have no translation yet; they are recorded as left empty.', '有 {n} 个句子还没有译文，将按“留空”记录。'],
  'pr.tr.recorded': ['{n} sentence(s) recorded. Translation is never graded - your marks stay yours.', '已记录 {n} 个句子。翻译从不评分 —— 你的标记只属于你。'],
  'pr.tr.noMarks': ['No marked spans yet. Select part of your translation, then choose how you feel about it.', '还没有标记的片段。选中译文的一部分，再选择你对它的感觉。'],
  'pr.tr.kindFor': ['Kind for the mark "{text}"', '标记“{text}”的类型'],
  'pr.tr.removeMark': ['Remove the mark "{text}"', '移除标记“{text}”'],
  'pr.tr.markedAs': ['Marked as: {kind}.', '已标记为：{kind}。'],
  'pr.tr.wholeSentence': ['Mark the whole sentence', '标记整个句子'],
  'pr.tr.noMark': ['No mark', '无标记'],
  'pr.tr.sentences': ['Sentences', '句子'],
  'pr.tr.chip': ['Sentence {n}, {state}{marked}', '第 {n} 句，{state}{marked}'],
  'pr.tr.chip.translated': ['translated', '已翻译'],
  'pr.tr.chip.notTranslated': ['not translated', '未翻译'],
  'pr.tr.chip.marked': [', marked', '，已标记'],
  'pr.tr.sentenceOf': ['Sentence {n} of {total}', '第 {n} 句 / 共 {total} 句'],
  'pr.tr.note': ['Note: {text}', '备注：{text}'],
  'pr.tr.yours': ['Your translation', '你的译文'],
  'pr.tr.markSelected': ['Mark the selected part of your translation', '标记所选的那部分译文'],
  'pr.tr.markSelection': ['Mark selection:', '标记所选：'],
  'pr.tr.wholeSentenceColon': ['Whole sentence: ', '整个句子：'],
  'pr.tr.reference': ['Reference translation', '参考译文'],
  'pr.tr.hideReference': ['Hide reference', '隐藏参考译文'],
  'pr.tr.showReference': ['Show reference translation', '显示参考译文'],
  'pr.tr.finish.title': ['Finish this practice?', '完成这次练习？'],
  'pr.tr.finish.keep': ['Keep working', '继续做'],
  'pr.tr.saved': ['Practice saved.', '练习已保存。'],
  'pr.tr.savedTitle': ['Practice saved', '练习已保存'],
  'pr.tr.retryMarked': ['Retry the {n} marked sentence(s)', '重做标记过的 {n} 个句子'],
  'pr.tr.retryAll': ['Retry everything', '全部重做'],
  // ---- Typing
  'pr.ty.count': ['{typed} of {total} characters typed', '已输入 {typed} / {total} 个字符'],
  'pr.ty.progress': ['{typed} of {total} characters', '{typed} / {total} 个字符'],
  'pr.ty.diffs': ['{n} difference(s) between the passage and what you typed.', '原文与你的输入之间有 {n} 处差异。'],
  'pr.ty.passage': ['passage: ', '原文：'],
  'pr.ty.typed': [' typed: ', ' 输入：'],
  'pr.ty.kindIs': ['. Difference kind: {kind}', '。差异类型：{kind}'],
  'pr.ty.more': ['…and {n} more.', '…另有 {n} 处。'],
  'pr.ty.different': ['Different', '打错'],
  'pr.ty.missed': ['Missed', '漏打'],
  'pr.ty.extra': ['Extra', '多打'],
  'pr.ty.tag': ['Typing · {intent}{note}', '跟打 · {intent}{note}'],
  'pr.ty.noteTest': [' · results after you finish', ' · 完成后显示结果'],
  'pr.ty.noteLive': [' · live feedback', ' · 实时反馈'],
  'pr.ty.reference': ['Reference text', '原文'],
  'pr.ty.typeHere': ['Type the passage here', '在这里输入这段文字'],
  'pr.ty.noPaste': ['Pasting and dropping text are turned off for copy typing - type the passage.', '跟打练习中已关闭粘贴和拖放文字 —— 请自己输入这段文字。'],
  'pr.ty.noPasteShort': ['Pasting is turned off for copy typing.', '跟打练习中已关闭粘贴。'],
  'pr.ty.early.title': ['Finish before the end?', '还没打完，现在就完成吗？'],
  'pr.ty.early.body': ['You have typed {typed} of {total} characters. The rest will count as missed.', '你已输入 {total} 个字符中的 {typed} 个，其余部分会计为漏打。'],
  'pr.ty.early.keep': ['Keep typing', '继续输入'],
  'pr.ty.savedFound': ['Saved. {n} difference(s) found.', '已保存。发现 {n} 处差异。'],
  'pr.ty.savedPerfect': ['Saved. No differences - a perfect copy.', '已保存。没有差异 —— 完全一致。'],
  'pr.ty.savedTitle': ['Practice saved', '练习已保存'],
  'pr.ty.none': ['No differences - what you typed matches the passage.', '没有差异 —— 你输入的和原文一致。'],
  'pr.ty.disclaimer': ['Typing differences describe this copy only; they are not a judgment of what you know.', '打字差异只描述这一次抄写，并不是对你掌握程度的判断。'],
  'pr.ty.again': ['Try this passage again', '再打一遍这段文字'],
});
